# Section 1

In [ ]:
import numpy as np

In [ ]:
range(15)

range(0, 15)

In [ ]:
list(range(15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [ ]:
f_matrix = np.random.randint(2, size=(10,5))
display(f_matrix)
f_labels = np.random.randint(187, size=(10,))
f_labels

array([[0, 0, 1, 1, 0],
       [1, 0, 0, 1, 1],
       [0, 0, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 1, 0, 1],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]])

array([  5,  23,  73,   1,  85, 131,  52,  30,  13, 125])

In [ ]:
index = np.arange(len(f_labels))
index

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
batch_size = 3
np.ceil(len(f_labels)/batch_size)

4.0

In [ ]:
display(index[:batch_size])
display(f_matrix[index[:batch_size]])
f_labels[index[:batch_size]]

array([0, 1, 2])

array([[0, 0, 1, 1, 0],
       [1, 0, 0, 1, 1],
       [0, 0, 0, 1, 0]])

array([ 5, 23, 73])

In [ ]:
np.random.shuffle(index)
index

array([6, 4, 1, 3, 9, 2, 5, 0, 8, 7])

In [ ]:
display(index[:batch])
display(f_matrix[index[:batch]])
f_labels[index[:batch]]

array([6, 4, 1])

array([[0, 1, 1, 0, 1],
       [1, 1, 0, 1, 0],
       [1, 0, 0, 1, 1]])

array([52, 85, 23])

In [ ]:
f = ['AAAAAGATTTTGAGAGAGGTCGACCTGTCCTCCTAAAACGTTTACAAAAG	71	0', 
 'CATGTAACGCAGCTTAGTCCGATCGTGGCTATAATCCGTCTTTCGATTTG	1	7', 
'AACAACATCTTGTTGATGATAACCGTCAAAGTGTTTTGGGTCTGGAGGGA	158	6']
f

['AAAAAGATTTTGAGAGAGGTCGACCTGTCCTCCTAAAACGTTTACAAAAG\t71\t0',
 'CATGTAACGCAGCTTAGTCCGATCGTGGCTATAATCCGTCTTTCGATTTG\t1\t7',
 'AACAACATCTTGTTGATGATAACCGTCAAAGTGTTTTGGGTCTGGAGGGA\t158\t6']

In [ ]:
f_matrix=[]
f_labels=[]
f_pos=[]
for i in f:
    i=i.strip().split("\t")
    print(i)
    f_matrix.append(i[0])
    f_labels.append(i[1])
    f_pos.append(i[2])
f_matrix,f_labels, f_pos

['AAAAAGATTTTGAGAGAGGTCGACCTGTCCTCCTAAAACGTTTACAAAAG', '71', '0']
['CATGTAACGCAGCTTAGTCCGATCGTGGCTATAATCCGTCTTTCGATTTG', '1', '7']
['AACAACATCTTGTTGATGATAACCGTCAAAGTGTTTTGGGTCTGGAGGGA', '158', '6']


(['AAAAAGATTTTGAGAGAGGTCGACCTGTCCTCCTAAAACGTTTACAAAAG',
  'CATGTAACGCAGCTTAGTCCGATCGTGGCTATAATCCGTCTTTCGATTTG',
  'AACAACATCTTGTTGATGATAACCGTCAAAGTGTTTTGGGTCTGGAGGGA'],
 ['71', '1', '158'],
 ['0', '7', '6'])

In [ ]:
seq = 'AGTACCTGGAGAGCGTTAAGAAACACAAACGGCTGGATGTAGTGCCGCGC'
seq_list=[j for j in seq]

# Section 2

# Others